services:
  - type: worker
    name: medusaxd-hosting-bot
    env: python
    plan: pro
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
    disk:
      name: bot-storage
      mountPath: /opt/render/project/src/user_data
      sizeGB: 10
